name: Build Angular + ASP.NET Core (Windows)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:   

jobs:
  build:
    runs-on: windows-latest

    env:
      BUILD_CONFIG: Release
      RUNTIME_ID: win-x64
      PUBLISH_DIR: publish_output

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Angular dependencies
        working-directory: filmssaver.client
        run: npm install

      - name: Build Angular app (production)
        working-directory: filmssaver.client
        run: npm run build -- --configuration production

      - name: Copy Angular dist to ASP.NET Core wwwroot
        run: |
            Remove-Item -Recurse -Force FilmsSaver.Server\wwwroot\* -ErrorAction SilentlyContinue
            Copy-Item -Recurse -Force filmssaver.client\dist\filmssaver.client\* FilmsSaver.Server\wwwroot\

      - name: Build ASP.NET Core backend
        run: dotnet build FilmsSaver.Server\FilmsSaver.Server.csproj --configuration ${{ env.BUILD_CONFIG }}

      - name: Publish ASP.NET Core app
        run: dotnet publish FilmsSaver.Server\FilmsSaver.Server.csproj --configuration ${{ env.BUILD_CONFIG }} --runtime ${{ env.RUNTIME_ID }} --self-contained false --output ${{ env.PUBLISH_DIR }}

          
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          ftp-server: ftp://194.164.55.146:21
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ${{ env.PUBLISH_DIR }}
          remote-dir: /FilmSaver
