name: Build Angular + ASP.NET Core (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Angular dependencies
      working-directory: filmssaver.client
      run: npm install

    - name: Build Angular app (production)
      working-directory: filmssaver.client
      run: npm run build -- --configuration production

    - name: Clean wwwroot folder
      run: Remove-Item -Recurse -Force FilmsSaver.Server\wwwroot\*

    - name: Copy Angular build files to wwwroot
      run: Copy-Item -Recurse -Force filmssaver.client\dist\filmssaver.client\* FilmsSaver.Server\wwwroot\

    - name: Publish ASP.NET Core project
      run: dotnet publish FilmsSaver.Server\FilmsSaver.Server.csproj -c Release -o published

    - name: (Optional) Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: published-app
        path: FilmsSaver.Server\published
